#!/bin/sh
sysctl -p /etc/sysctl-dolly.conf
iptables -t nat -F
ip6tables -t nat -F
iptables -t nat -I POSTROUTING -o dolly -m policy --dir out --pol ipsec -j ACCEPT
iptables -t nat -I POSTROUTING -o dolly -j MASQUERADE
#ip6tables -t nat -I POSTROUTING -o dolly -j MASQUERADE
true
